### ISSUE TITLE
Katalogi

### ISSUE THREAD

**Issue by danijel3** [speech-clarin-pl/clarin-pl-api#2]
Trzeba zmienić katalogi repo:

- katalog uploaded_tmp najlepiej zmienić na '/tmp' albo coś podobnego
- katalog repo powinien być pusty i będzie montowany z systemu hosta
- katalog demo_files powinien być gdzieś na zewnątrz repo, najprościej '/app/demo_files'

**Comment by mklec** [comment]
Zrobione
